version: "3.8"

services:
  nginx-mtls:
    image: nginx
    volumes:
      - ./certs/server.crt:/etc/nginx/certificates/server.crt
      - ./certs/server.key:/etc/nginx/certificates/server.key
      - ./certs/client-ca.crt:/etc/nginx/certificates/client-ca.crt
      - ./nginx-mtls/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-mtls/hello-world.txt:/www/data/hello-world.txt
    ports:
      - "8889:8889"
