version: "3.9"

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  oracle:
    image: quay.io/maksymbilenko/oracle-12c
    platform: linux/x86_64
    environment:
      USER: godev_user
      PASS: godev_pass
      SID: godev
      # ORACLE_PASSWORD: mysecretpassword
      # ORACLE_DATABASE: godev
      # TARGET_PDB: godev
      # APP_USER: godev_user
      # APP_USER_PASSWORD: godev_pass
    volumes:
      - ./docker/oracle/custom-healthcheck.sh:/opt/oracle/custom-healthcheck.sh
      - ./docker/oracle/custom-healthcheck.sql:/opt/oracle/custom-healthcheck.sql
      - oracle_data:/opt/oracle/oradata
    ports:
      - '1521:1521'
    healthcheck:
      test: ['CMD', 'sh', 'custom-healthcheck.sh']
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 20s


volumes:
  oracle_data: